apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.teams: |
    recipientUrls:
      channelName: $channel-teams-url
  template.app-sync-succeeded: |
    teams:
      themeColor: "#000080"
      sections: |
        [{
          "facts": [
            {
              "name": "Sync Status",
              "value": "{{.app.status.sync.status}}"
            },
            {
              "name": "Repository",
              "value": "{{.app.spec.source.repoURL}}"
            }
          ]
        }]
      potentialAction: |-
        [{
          "@type":"OpenUri",
          "name":"Operation Details",
          "targets":[{
            "os":"default",
            "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
          }]
        }]
      title: Application {{.app.metadata.name}} has been successfully synced
      text: Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
      summary: "{{.app.metadata.name}} sync succeeded"
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  channel-teams-url: https://heidelpay.webhook.office.com/webhookb2/089337dd-eb06-4da4-b156-7e537756d14a@797b2bda-888b-44ab-9967-3c9448c99377/IncomingWebhook/51d969261ebf4593a120a46662a258ba/6e5a713c-530e-44bf-b037-fd5f771139ec